version: '3.9'

services:
  app:
    env_file:
      - .env
    container_name: ce-boostup-xii
    image: ce-boostup-xii
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080